const fs = require('fs');
const path = require('path');
const {
  TAXONOMY_DATA,
  TAXONOMY,
  ALL_SUBJECTS,
  ALL_CHAPTERS,
  CHAPTER_NAMES,
  SUBJECT_NAMES,
  CHAPTER_TO_SUBJECT,
} = require('../data/taxonomy');

const targetFilePath = path.resolve(__dirname, '../../frontend/scripts/chapterNames.js');

const generateContent = () => {
  return `// AUTOGENERATED FROM backend/data/taxonomy.js - DO NOT EDIT DIRECTLY
// To update, edit backend/data/taxonomy.js and run 'npm run build:taxonomy'

const TAXONOMY_DATA = ${JSON.stringify(TAXONOMY_DATA, null, 2)};

const TAXONOMY = ${JSON.stringify(TAXONOMY, null, 2)};

const ALL_SUBJECTS = ${JSON.stringify(ALL_SUBJECTS, null, 2)};

const ALL_CHAPTERS = ${JSON.stringify(ALL_CHAPTERS, null, 2)};

const CHAPTER_NAMES = ${JSON.stringify(CHAPTER_NAMES, null, 2)};

const SUBJECT_NAMES = ${JSON.stringify(SUBJECT_NAMES, null, 2)};

const chapterSubjects = ${JSON.stringify(CHAPTER_TO_SUBJECT, null, 2)};

function getChapterTitle(chapter) {
  return CHAPTER_NAMES[chapter] || chapter;
}

function getSubjectTitle(subject) {
  return SUBJECT_NAMES[subject] || subject;
}

function getChapterSubject(chapter) {
  return chapterSubjects[chapter];
}

function getSubjectChapters(subject) {
  const s = typeof subject === 'string' ? subject.toLowerCase().trim() : '';
  if (!TAXONOMY_DATA[s]) return [];
  return TAXONOMY_DATA[s].chapters;
}
`;
};

const build = () => {
  const content = generateContent();
  fs.writeFileSync(targetFilePath, content, 'utf8');
  console.log(`[Taxonomy Builder] Successfully generated ${targetFilePath} from canonical backend taxonomy.`);
};

if (require.main === module) {
  build();
}

module.exports = {
  build,
  generateContent,
};
