// AUTOGENERATED FROM backend/data/taxonomy.js - DO NOT EDIT DIRECTLY
// To update, edit backend/data/taxonomy.js and run 'npm run build:taxonomy'

const TAXONOMY_DATA = {
  "physics": {
    "displayName": "Physics",
    "chapters": [
      {
        "id": "kinematics",
        "name": "Kinematics"
      },
      {
        "id": "nlm",
        "name": "Newton's Laws"
      },
      {
        "id": "wpe",
        "name": "Work Power Energy"
      },
      {
        "id": "rotational",
        "name": "Rotational Motion"
      }
    ]
  },
  "chemistry": {
    "displayName": "Chemistry",
    "chapters": [
      {
        "id": "atomicstructure",
        "name": "Atomic Structure"
      },
      {
        "id": "chemicalbonding",
        "name": "Chemical Bonding"
      },
      {
        "id": "thermodynamics",
        "name": "Thermodynamics"
      },
      {
        "id": "electrochemistry",
        "name": "Electrochemistry"
      }
    ]
  },
  "maths": {
    "displayName": "Maths",
    "chapters": [
      {
        "id": "quadraticequations",
        "name": "Quadratic Equations"
      },
      {
        "id": "sequences",
        "name": "Sequences & Series"
      },
      {
        "id": "limits",
        "name": "Limits & Derivatives"
      },
      {
        "id": "matrices",
        "name": "Matrices"
      }
    ]
  }
};

const TAXONOMY = {
  "physics": [
    "kinematics",
    "nlm",
    "wpe",
    "rotational"
  ],
  "chemistry": [
    "atomicstructure",
    "chemicalbonding",
    "thermodynamics",
    "electrochemistry"
  ],
  "maths": [
    "quadraticequations",
    "sequences",
    "limits",
    "matrices"
  ]
};

const ALL_SUBJECTS = [
  "physics",
  "chemistry",
  "maths"
];

const ALL_CHAPTERS = [
  "kinematics",
  "nlm",
  "wpe",
  "rotational",
  "atomicstructure",
  "chemicalbonding",
  "thermodynamics",
  "electrochemistry",
  "quadraticequations",
  "sequences",
  "limits",
  "matrices"
];

const CHAPTER_NAMES = {
  "kinematics": "Kinematics",
  "nlm": "Newton's Laws",
  "wpe": "Work Power Energy",
  "rotational": "Rotational Motion",
  "atomicstructure": "Atomic Structure",
  "chemicalbonding": "Chemical Bonding",
  "thermodynamics": "Thermodynamics",
  "electrochemistry": "Electrochemistry",
  "quadraticequations": "Quadratic Equations",
  "sequences": "Sequences & Series",
  "limits": "Limits & Derivatives",
  "matrices": "Matrices"
};

const SUBJECT_NAMES = {
  "physics": "Physics",
  "chemistry": "Chemistry",
  "maths": "Maths"
};

const chapterSubjects = {
  "kinematics": "physics",
  "nlm": "physics",
  "wpe": "physics",
  "rotational": "physics",
  "atomicstructure": "chemistry",
  "chemicalbonding": "chemistry",
  "thermodynamics": "chemistry",
  "electrochemistry": "chemistry",
  "quadraticequations": "maths",
  "sequences": "maths",
  "limits": "maths",
  "matrices": "maths"
};

function getChapterTitle(chapter) {
  return CHAPTER_NAMES[chapter] || chapter;
}

function getSubjectTitle(subject) {
  return SUBJECT_NAMES[subject] || subject;
}

function getChapterSubject(chapter) {
  return chapterSubjects[chapter];
}

function getSubjectChapters(subject) {
  const s = typeof subject === 'string' ? subject.toLowerCase().trim() : '';
  if (!TAXONOMY_DATA[s]) return [];
  return TAXONOMY_DATA[s].chapters;
}
